name: flutter_2048
description: 2048 Game built using AnimatedWidget and Explicit Animations.

publish_to: "none"

version: 1.2.0+2

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  provider: ^6.1.2
  get_it: any
  injectable: ^2.4.4
  rxdart: ^0.27.7
  shared_preferences: ^2.5.3

  uuid: ^3.0.6
  sprintf: ^7.0.0

  flutter_svg: ^2.2.0
  easy_localization: ^3.0.7
  url_launcher: ^6.3.1

  hive: ^2.1.1
  hive_flutter: ^1.1.0

  json_annotation: ^4.11.0

  flutter_core:
    path: packages/core/flutter_core
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: any
  injectable_generator: any

  flutter_lints: ^2.0.0

  build_runner: ^2.1.11

  json_serializable: ^6.2.0

flutter_gen:
  output: lib/resource/

flutter:
  uses-material-design: true
  assets:
    - assets/locale/
    - assets/images/
